// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot.commands;

import java.io.IOException;
import java.nio.file.Path;
import java.util.List;

import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.math.controller.RamseteController;
import edu.wpi.first.math.controller.SimpleMotorFeedforward;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.DifferentialDriveKinematics;
import edu.wpi.first.math.trajectory.Trajectory;
import edu.wpi.first.math.trajectory.TrajectoryConfig;
import edu.wpi.first.math.trajectory.TrajectoryGenerator;
import edu.wpi.first.math.trajectory.TrajectoryUtil;
import edu.wpi.first.math.trajectory.constraint.DifferentialDriveVoltageConstraint;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.Filesystem;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.RamseteCommand;
import frc.robot.Constants;
import frc.robot.subsystems.Drivetrain;

/** Utility class to generate Ramsete path following commands.
 *   Examples included for generating path manually and from file generated by PathWeaver.
 */
public final class pathCommands {
   
    private static final DifferentialDriveKinematics kDriveKinematics =
        new DifferentialDriveKinematics(Constants.kTrackWidth);

    public static Command getRamseteManual(Drivetrain robotDrive) {

        Trajectory manualTrajectory = getManualTrajectory();
        
        // Set starting pose and show the trajectory on the field
        robotDrive.resetOdometry(new Pose2d(Constants.startX, Constants.startY, new Rotation2d()));
        robotDrive.showTrajectory(manualTrajectory);

        return getRamseteCommand(manualTrajectory, robotDrive);
            
    }

    public static Command getRamseteFromFile(Drivetrain robotDrive) {

        Trajectory fileTrajectory = getFileTrajectory();
        
        // Set starting pose and show the trajectory on the field
        robotDrive.resetOdometry(new Pose2d(Constants.startX, Constants.startY, new Rotation2d()));
        robotDrive.showTrajectory(fileTrajectory);

        return getRamseteCommand(fileTrajectory, robotDrive);
            
    }

    // Create a trajectory from a list of points.  All units in meters.
    public static Trajectory getManualTrajectory () {

        // Create a voltage constraint to ensure we don't accelerate too fast
        var autoVoltageConstraint =
            new DifferentialDriveVoltageConstraint(
                new SimpleMotorFeedforward(
                    Constants.ksVolts,
                    Constants.kvVoltSecondsPerMeter,
                    Constants.kaVoltSecondsSquaredPerMeter),
                kDriveKinematics,
                10);

        // Create config for trajectory
        TrajectoryConfig config =
            new TrajectoryConfig(
                    Constants.kMaxSpeedMetersPerSecond,
                    Constants.kMaxAccelMetersPerSecondSquared)
                // Add kinematics to ensure max speed is actually obeyed
                .setKinematics(kDriveKinematics)
                // Apply the voltage constraint
                .addConstraint(autoVoltageConstraint);

        return TrajectoryGenerator.generateTrajectory(
            // Start at the origin facing the +X direction
            new Pose2d(Constants.startX, Constants.startY, new Rotation2d(0)),
            // Pass through these two interior waypoints, making an 's' curve path
            // List.of(new Translation2d(2.2, 1.2), new Translation2d(2.7,0.8)),
            List.of(new Translation2d(2.1, 5.1), new Translation2d(2.6,4.3)),
            // End 2 meters ahead of where we started, facing forward
            new Pose2d(3.1, 4.7, new Rotation2d(0)),
            // Pass config
            config);

    }

    // Import a trajectory from PathWeaver JSON file
    private static Trajectory getFileTrajectory() {

        String trajectoryJSON = "paths/two_cups.wpilib.json";
        Trajectory trajectoryFromJSON = null;

        try {
        Path trajectoryPath = Filesystem.getDeployDirectory().toPath().resolve(trajectoryJSON);
        trajectoryFromJSON = TrajectoryUtil.fromPathweaverJson(trajectoryPath);
        } catch (IOException ex) {
        DriverStation.reportError("Unable to open trajectory: " + trajectoryJSON, ex.getStackTrace());
        } 

        return trajectoryFromJSON;

    }

    // Get a Ramsete command for the trajectory
    private static Command getRamseteCommand(Trajectory trajectory, Drivetrain robotDrive) {
            return new RamseteCommand(
                trajectory,
                robotDrive::getPose,
                new RamseteController(Constants.kRamseteB, Constants.kRamseteZeta),
                new SimpleMotorFeedforward(
                    Constants.ksVolts,
                    Constants.kvVoltSecondsPerMeter,
                    Constants.kaVoltSecondsSquaredPerMeter),
                kDriveKinematics,
                robotDrive::getWheelSpeeds,
                new PIDController(Constants.kPDriveVel, 0, 0),
                new PIDController(Constants.kPDriveVel, 0, 0),
                // RamseteCommand passes volts to the callback
                robotDrive::tankDriveVolts,
                robotDrive);
    }


}
